# Generated by Django 4.0.1 on 2022-01-24 18:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('minecraft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 24, 18, 38, 36, 587401, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
